services:
  app:
    image: ghcr.io/rvoltz/quotefy:8ee3e9e5b1cf099b2d7d9996a25a48fd40a8a5e3
    env_file: [app.env]
    depends_on: []
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: PRD_DB_PASSWORD_V2
        target: DB_PASSWORD
      - source: PRD_ASAAS_ACCESS_TOKEN
        target: ASAAS_ACCESS_TOKEN
    ports:
      - target: 8080
        published: 62091
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

  whatsapp-api:
    image: ghcr.io/rvoltz/quotefy-whatsapp-api:52e6a9737e1922ee22b72325f4eea88c2c2baca0
    env_file: [whatsapp.env]
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: PRD_DB_PASSWORD_V2
        target: DB_PASSWORD
      - source: PRD_WHATSAPP_API_KEY_V2
        target: WHATSAPP_API_KEY
    networks:
      - quotefy-net

networks:
  quotefy-net:
    driver: overlay
    attachable: true

secrets:
  PRD_DB_PASSWORD_V2:
    external: true
  PRD_WHATSAPP_API_KEY_V2:
    external: true
  PRD_ASAAS_ACCESS_TOKEN:
    external: true
