services:
  app:
    image: ghcr.io/rvoltz/quotefy:6da596fe0b3b5fb951ccbcbb19b9b127d5e03e7c
    env_file: [app.env]
    depends_on: []
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: PRD_DB_PASSWORD_V2
        target: DB_PASSWORD
      - source: PRD_ASAAS_ACCESS_TOKEN
        target: ASAAS_ACCESS_TOKEN
    ports:
      - target: 8080
        published: 62091
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

  whatsapp-api:
    image: ghcr.io/rvoltz/quotefy-whatsapp-api:da822f96ec4f52d4434076064fe96b896ca2e3b0
    env_file: [whatsapp.env]
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: PRD_DB_PASSWORD_V2
        target: DB_PASSWORD
      - source: PRD_WHATSAPP_API_KEY_V2
        target: WHATSAPP_API_KEY
    networks:
      - quotefy-net

networks:
  quotefy-net:
    driver: overlay
    attachable: true

secrets:
  PRD_DB_PASSWORD_V2:
    external: true
  PRD_WHATSAPP_API_KEY_V2:
    external: true
  PRD_ASAAS_ACCESS_TOKEN:
    external: true
