services:
  app:
    image: ghcr.io/rvoltz/quotefy:a00697b5131341aa8c98a7a6f290fcc0be14f660
    env_file: [app.env]
    depends_on: []
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: PRD_DB_PASSWORD_V3
        target: DB_PASSWORD
      - source: PRD_ASAAS_ACCESS_TOKEN
        target: ASAAS_ACCESS_TOKEN
      - source: PRD_ASAAS_WEBHOOK_SECRET
        target: ASAAS_WEBHOOK_SECRET
      - source: PRD_BREVO_API_KEY
        target: BREVO_API_KEY
      - source: PRD_BREVO_WEBHOOK_SECRET
        target: BREVO_WEBHOOK_SECRET
      - source: PRD_JWT_SECRET_V2
        target: JWT_SECRET
      - source: PRD_STORAGE_ACCESS_KEY_V2
        target: STORAGE_ACCESS_KEY
      - source: PRD_STORAGE_SECRET_KEY_V2
        target: STORAGE_SECRET_KEY
      - source: PRD_LICENSE_PLATE_TOKEN
        target: LICENSE_PLATE_TOKEN
      - source: PRD_TOGETHER_API_KEY
        target: TOGETHER_API_KEY
      - source: PRD_GEMINI_API_KEY
        target: GEMINI_API_KEY
      - source: PRD_WHATSAPP_API_KEY_V2
        target: WHATSAPP_API_KEY
    ports:
      - target: 8080
        published: 62091
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

  whatsapp-api:
    image: ghcr.io/rvoltz/quotefy-whatsapp-api:da822f96ec4f52d4434076064fe96b896ca2e3b0
    env_file: [whatsapp.env]
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: PRD_DB_PASSWORD_V3
        target: DB_PASSWORD
      - source: PRD_WHATSAPP_API_KEY_V2
        target: WHATSAPP_API_KEY
    networks:
      - quotefy-net

networks:
  quotefy-net:
    driver: overlay
    attachable: true

secrets:
  PRD_DB_PASSWORD_V3:
    external: true
  PRD_WHATSAPP_API_KEY_V2:
    external: true
  PRD_ASAAS_ACCESS_TOKEN:
    external: true
  PRD_ASAAS_WEBHOOK_SECRET:
    external: true
  PRD_BREVO_API_KEY:
    external: true
  PRD_BREVO_WEBHOOK_SECRET:
    external: true
  PRD_JWT_SECRET_V2:
    external: true
  PRD_STORAGE_ACCESS_KEY_V2:
    external: true
  PRD_STORAGE_SECRET_KEY_V2:
    external: true
  PRD_LICENSE_PLATE_TOKEN:
    external: true
  PRD_TOGETHER_API_KEY:
    external: true
  PRD_GEMINI_API_KEY:
    external: true
