services:
  frontend:
    image: ghcr.io/rvoltz/quotefy-front-app:6e0b571748b936139a03faf1e0da53784b84dbe3
    env_file: [front.env]
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 62080
        protocol: tcp
        mode: host
    networks:
      - quotefy-back-hml_quotefy-net

networks:
  quotefy-back-hml_quotefy-net:
    external: true
