services:
  frontend:
    image: ghcr.io/rvoltz/quotefy-front-app:7fa7de4c9fa0e4ad6182989c20b12d5cc9a09db2
    env_file: [front.env]
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 62080
        protocol: tcp
        mode: host
    networks:
      - quotefy-back-hml_quotefy-net

networks:
  quotefy-back-hml_quotefy-net:
    external: true
