services:
  db:
    image: postgres:15.4-alpine
    env_file: [db.env]
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: DB_PASSWORD
        target: DB_PASSWORD
    ports:
      - target: 5432
        published: 65432 # Porta publicada para o DB original
        protocol: tcp
        mode: host
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - quotefy-net

  app:
    image: ghcr.io/rvoltz/quotefy:1466260c97a9283e38f4b0258451d241c9656b63
    env_file: [app.env]
    depends_on:
      - db # Depende do serviço de DB
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: DB_PASSWORD
        target: DB_PASSWORD
      - source: HML_ASAAS_ACCESS_TOKEN
        target: ASAAS_ACCESS_TOKEN
      - source: HML_ASAAS_WEBHOOK_SECRET
        target: ASAAS_WEBHOOK_SECRET
      - source: HML_BREVO_API_KEY
        target: BREVO_API_KEY
      - source: HML_BREVO_WEBHOOK_SECRET
        target: BREVO_WEBHOOK_SECRET
      - source: HML_JWT_SECRET
        target: JWT_SECRET
      - source: HML_STORAGE_ACCESS_KEY
        target: STORAGE_ACCESS_KEY
      - source: HML_STORAGE_SECRET_KEY
        target: STORAGE_SECRET_KEY
      - source: HML_LICENSE_PLATE_TOKEN
        target: LICENSE_PLATE_TOKEN
      - source: HML_TOGETHER_API_KEY
        target: TOGETHER_API_KEY
      - source: HML_GEMINI_API_KEY
        target: GEMINI_API_KEY
      - source: WHATSAPP_API_KEY
        target: WHATSAPP_API_KEY
    ports:
      - target: 8080
        published: 62090
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

  whatsapp-api:
    image: ghcr.io/rvoltz/quotefy-whatsapp-api:da822f96ec4f52d4434076064fe96b896ca2e3b0
    env_file: [whatsapp.env]
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    secrets:
      - DB_PASSWORD
      - WHATSAPP_API_KEY
    ports:
      - target: 3000
        published: 63000
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

networks:
  quotefy-net:
    driver: overlay
    attachable: true

volumes:
  db-data:

secrets:
  DB_PASSWORD:
    external: true
  WHATSAPP_API_KEY:
    external: true
  HML_ASAAS_ACCESS_TOKEN:
    external: true
  HML_ASAAS_WEBHOOK_SECRET:
    external: true
  HML_BREVO_API_KEY:
    external: true
  HML_BREVO_WEBHOOK_SECRET:
    external: true
  HML_JWT_SECRET:
    external: true
  HML_STORAGE_ACCESS_KEY:
    external: true
  HML_STORAGE_SECRET_KEY:
    external: true
  HML_LICENSE_PLATE_TOKEN:
    external: true
  HML_TOGETHER_API_KEY:
    external: true
  HML_GEMINI_API_KEY:
    external: true