services:
  db:
    image: postgres:15.4-alpine
    env_file: [db.env]
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: DB_PASSWORD
        target: DB_PASSWORD
    ports:
      - target: 5432
        published: 65432 # Porta publicada para o DB original
        protocol: tcp
        mode: host
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - quotefy-net

  app:
    image: ghcr.io/rvoltz/quotefy:b24a815b5dd4d3b295a00b4141dc86c76c2018da
    env_file: [app.env]
    depends_on:
      - db # Depende do serviço de DB
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - source: DB_PASSWORD
        target: DB_PASSWORD
      - source: HML_ASAAS_ACCESS_TOKEN
        target: ASAAS_ACCESS_TOKEN
    ports:
      - target: 8080
        published: 62090
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

  whatsapp-api:
    image: ghcr.io/rvoltz/quotefy-whatsapp-api:a9693efb8368c33a51191d20ea6a4e3d45f48bf8
    env_file: [whatsapp.env]
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    secrets:
      - DB_PASSWORD
      - WHATSAPP_API_KEY
    ports:
      - target: 3000
        published: 63000
        protocol: tcp
        mode: host
    networks:
      - quotefy-net

networks:
  quotefy-net:
    driver: overlay
    attachable: true

volumes:
  db-data:

secrets:
  DB_PASSWORD:
    external: true
  WHATSAPP_API_KEY:
    external: true
  HML_ASAAS_ACCESS_TOKEN:
    external: true