services:
  frontend:
    image: ghcr.io/rvoltz/quotefy-front-app:5e8c7608d839a6287fe26e45c9316434dc27aef7-prd
    env_file: [front.env]
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 62081
        protocol: tcp
        mode: host
    networks:
      - quotefy-back-prd_quotefy-net

networks:
  quotefy-back-prd_quotefy-net:
    external: true
